#ifndef FRAG_CODE_H_
# define FRAG_CODE_H_
# define VAR_BACKGROUNDCOLOR "i"
# define VAR_BASECOLOR "V"
# define VAR_COLORITERATIONS "D"
# define VAR_CYCLECOLORS "q"
# define VAR_CYCLES "e"
# define VAR_FUDGEFACTOR "d"
# define VAR_GRADIENTBACKGROUND "t"
# define VAR_HITDISTANCE "y"
# define VAR_ITERATIONS "E"
# define VAR_OFFSET "ab"
# define VAR_ORBITSTRENGTH "U"
# define VAR_R "Q"
# define VAR_RAYBOUNCES "Y"
# define VAR_RAYSTEPS "X"
# define VAR_ROTANGLE "j"
# define VAR_ROTVECTOR "A"
# define VAR_SCALE "B"
# define VAR_SHADOWSTEPS "W"
# define VAR_SUNSTRENGTH "p"
# define VAR_USECHEAPSPECULAR "F"
# define VAR_USEEMISSIVE "h"
# define VAR_USEGLOW "C"
# define VAR_X "T"
# define VAR_Y "S"
# define VAR_YOFF "ad"
# define VAR_Z "R"
# define VAR_OB1COLOR "z"
# define VAR_OB1POSITION "r"
# define VAR_OB1REFLECT "n"
# define VAR_OB1SPEC "l"
# define VAR_OB1SPECEXP "M"
# define VAR_GLOWCOLOR "f"
# define VAR_GLOWDIVISOR "o"
# define VAR_GLOWSTRENGTH "b"
# define VAR_LIGHTBLOOM "s"
# define VAR_LIGHTCOLOR "w"
# define VAR_LIGHTPOSITION "a"
# define VAR_LIGHTSTRENGTH "k"
# define VAR_OB2COLOR "c"
# define VAR_OB2REFLECT "g"
# define VAR_OB2SPEC "u"
# define VAR_OB2SPECEXP "Z"
# define VAR_SKYCOLOR "x"
# define VAR_SUNCOLOR "v"
# define VAR_SUNDIRECTION "m"

const char *frag_frag =
 "uniform vec3 v,i,f,y,x,z,d,c,m,r,a,w,s;"
 "uniform float p,e,b,t,o,n,l,g,u,k;"
 "uniform bool C,h,F,q;"
 "uniform int M,Z,Y,X,W;"
 "uniform vec3 V;"
 "uniform float U;"
 "uniform vec4 T,S,R,Q;"
 "vec3 P=vec3(0.,0.,0.);"
 "vec4 O=vec4(10000.);"
 "const float N=100.;"
 "int L=X;"
 "float K=2000.-pow(k,.001)*2000.,J=5e+06-pow(s,.01)*5e+06,I,H=1.;"
 "vec3 G=normalize(m);"
 "uniform int E,D;"
 "uniform float B;"
 "uniform vec3 A;"
 "uniform float j;"
 "uniform vec3 ab;"
 "mat3 ac;"
 "uniform float ad;"
 "const mat2 ae=mat2(.84147,.5403,.5403,-.84147);"
 "int af=0;"
 "vec3 ag=vec3(y*.1,0.,0.);"
 "vec2 ah=fract(cos(gl_FragCoord.xy+gl_FragCoord.yx*vec2(1000.,1000.)+vec2(backbufferCounter,backbufferCounter))*10000.);"
 "vec3 ai(vec3 a,float v)"
 "{"
   "return vec3(.5)+.5*vec3(cos(v*e+a.x),cos(v*e+a.y),cos(v*e+a.z));"
 "}"
 "vec3 ai()"
 "{"
   "O.w=sqrt(O.w)*5.;"
   "vec3 v;"
   "if(q)"
     "v=ai(T.xyz,O.x)*T.w*O.x+ai(S.xyz,O.y)*S.w*O.y+ai(R.xyz,O.z)*R.w*O.z+ai(Q.xyz,O.w)*Q.w*O.w;"
   "else"
     " v=T.xyz*T.w*O.x+S.xyz*S.w*O.y*30+R.xyz*R.w*O.z*20+Q.xyz*Q.w*O.w*200;"
   "vec3 a=mix(V,3.*v,U);"
   "return a;"
 "}"
 "float aj(in vec3 v,float a)"
 "{"
   "return length(v)-a;"
 "}"
 "void aj()"
 "{"
   "ac=rotationMatrix3(normalize(A),j);"
 "}"
 "float ai(vec3 v)"
 "{"
   "float a;"
   "int i=0;"
   "while(i<E&&dot(v,v)<10000.)"
     "{"
       "v.xy=abs(v.xy);"
       "if(v.y>v.x)"
         "v.xy=v.yx;"
       "v.y=ad-abs(v.y-ad);"
       "v.x+=1./3.;"
       "if(v.z>v.x)"
         "v.xz=v.zx;"
       "v.x-=1./3.;"
       "v.x-=1./3.;"
       "if(v.z>v.x)"
         "v.xz=v.zx;"
       "v.x+=1./3.;"
       "v=B*(v-ab)+ab;"
       "v=ac*v;"
       "a=dot(v,v);"
       "if(i<D)"
         "O=min(O,abs(vec4(v,a)));"
       "i++;"
     "}"
   "return abs(length(v)-length(ab))*pow(B,float(-i));"
 "}"
 "float aj(in float v)"
 "{"
   "return fract(sin(v)*43758.5);"
 "}"
 "float ak(in vec2 v)"
 "{"
   "vec2 a=floor(v),i=fract(v);"
   "i=i*i*(3.-2.*i);"
   "float y=a.x+a.y*57.,f=mix(mix(aj(y),aj(y+1.),i.x),mix(aj(y+57.),aj(y+58.),i.x),i.y);"
   "return f;"
 "}"
 "float al(in vec2 v)"
 "{"
   "float a;"
   "a=.5*ak(v);"
   "v=ae*v*2.02;"
   "a+=.25*ak(v);"
   "v=ae*v*2.33;"
   "return a/.9375;"
 "}"
 "float am(in vec3 v)"
 "{"
   "return v-=a,aj(v,.1);"
 "}"
 "vec2 an(in vec3 v)"
 "{"
   "float a=0,i=0,y=ai(v),x=aj(v-vec3(0.,0.,.1+al(v.xy)),.15);"
   "a=y<x?1:a;"
   "i=min(y,x);"
   "i=y;"
   "float f=h?am(v):1000.;"
   "I=min(I,f);"
   "a=f<i?-2:a;"
   "return vec2(i,a);"
 "}"
 "float ao(in vec3 v)"
 "{"
   "return am(v);"
 "}"
 "vec3 ai(in vec3 v,in vec3 a,in float y)"
 "{"
   "if(y==0.)"
     "return z*(al(v.xy*30.)/2.+.5);"
   "if(y==1.)"
     "return ai();"
   "return vec3(0.,0.,1.);"
 "}"
 "vec3 ak(in vec3 v,in float a)"
 "{"
   "if(a==0.)"
     "vec3(n,l,M);"
   "if(a==1.)"
     "vec3(g,u,Z);"
   "return vec3(0.,0.,1.);"
 "}"
 "vec3 ap(in vec3 a)"
 "{"
   "return x+v*(max(0.,dot(a,G))*.2+pow(max(0.,dot(a,G)),256.));"
 "}"
 "vec2 al(in vec3 v,in vec3 a)"
 "{"
   "float i=y*5.;"
   "H=sign(an(v+i*a).x);"
   "vec2 f=vec2(-1.),O=vec2(H*d,1.);"
   "for(int x=0;x<L&&i<N;x++)"
     "{"
       "af++;"
       "f=an(v+i*a)*O;"
       "i+=f.x;"
       "if(abs(f.x)<y)"
         "return vec2(i,f.y);"
     "}"
   "return vec2(i,i<N?f.y:-1.);"
 "}"
 "vec3 am(in vec3 v,in float a)"
 "{"
   "return H*normalize(vec3(-an(v-ag.xyy).x+an(v+ag.xyy).x,-an(v-ag.yxy).x+an(v+ag.yxy).x,-an(v-ag.yyx).x+an(v+ag.yyx).x));"
 "}"
 "vec3 aj(in vec3 v,in vec3 a,float y)"
 "{"
   "vec3 i=vec3(1.);"
   "for(int f=0;f<Y&&dot(i,i)>.001;f++)"
     "{"
       "vec2 O=al(v,a);"
       "if(O.y<0.)"
         "return vec3(float(O.y==y));"
       "else"
         "{"
           "float x=ak(v,O.y).x;"
           "if(x>=-.5&&x<.5)"
             "return vec3(0.);"
           "v+=a*O.x;"
           "vec3 z=am(v,O.y);"
           "i*=ai(v,z,O.y)*abs(x);"
           "vec3 d=H>=0.?refract(a,z,.75):refract(a,z,1.33);"
           "if(dot(d,z)<-.05&&x<0.)"
             "a=d;"
           "else"
             " a=reflect(a,z);"
         "}"
     "}"
   "return i;"
 "}"
 "vec2 ak()"
 "{"
   "return ah+=vec2(1.,1.),vec2(fract(sin(dot(ah.xy,vec2(12.9898,78.233)))*43758.5),fract(cos(dot(ah.xy,vec2(4.898,7.23)))*23421.6));"
 "}"
 "vec3 ak(vec3 v,float a,float y)"
 "{"
   "vec2 i=ak()*vec2(6.28319,y);"
   "vec3 x=cross(v,abs(v.x)<.5?vec3(1.,0.,0.):vec3(0.,1.,0.)),O=cross(v,x);"
   "i.y=pow(1.-i.y,1./a);"
   "float f=sqrt(1.-i.y*i.y);"
   "return cos(i.x)*f*x+sin(i.x)*f*O+i.y*v;"
 "}"
 "vec3 ai(inout vec3 a,in vec3 i,in vec3 y,in vec3 x,in float f)"
 "{"
   "float O=H,z=I;"
   "L=W;"
   "vec3 r=vec3(0.),d=ak(x,1.,1.),e=ap(d)*aj(y,d,-1.);"
   "d=ak(G,1.,.001);"
   "if(dot(d,x)>0.)"
     "{"
       "vec3 m=aj(y,d,-1.);"
       "if(dot(m,m)>0.)"
         "e+=dot(d,x)*m*v*p;"
     "}"
   "if(!F&&ak(y,f).y>0.)"
     "{"
       "d=ak(reflect(i,x),ak(y,f).z,1.);"
       "if(dot(d,G)>.9)"
         "r+=ak(y,f).y*a*v*p*aj(y,d,-1.);"
     "}"
   "if(h)"
     "{"
       "vec2 m=vec2(ao(y),0.);"
       "d=-normalize(vec3(-ao(y-m.xyy)+ao(y+m.xyy),-ao(y-m.yxy)+ao(y+m.yxy),-ao(y-m.yyx)+ao(y+m.yyx)));"
       "vec3 c=w/max(K*m.x*m.x,1.);"
       "if(!F&&ak(y,f).y>0.)"
         "d=ak(reflect(i,x),ak(y,f).z,1.),r+=ak(y,f).y*a*c*aj(y,d,-2.);"
       "d=ak(d,1.,.001/max(m.x*m.x,1.));"
       "if(dot(d,x)>0.)"
         "{"
           "vec3 n=aj(y,d,-2.);"
           "if(dot(n,n)>0.)"
             "{"
               "e+=c*dot(x,d)*n;"
               "if(F)"
                 "r+=ak(y,f).y*a*c*pow(max(0.,dot(i,reflect(d,x))),ak(y,f).z);"
             "}"
         "}"
     "}"
   "H=O;"
   "I=z;"
   "L=X;"
   "a*=ai(y,x,f);"
   "return a*e+r;"
 "}"
 "vec3 ai(in vec3 v,in vec3 a,in vec3 y,in float f)"
 "{"
   "float i=ak(y,f).x;"
   "if(ak().x>abs(i))"
     "return ak(v,1.,1.);"
   "else"
     "{"
       "vec3 x=reflect(a,v);"
       "if(i<0.)"
         "{"
           "if(ak().x<.75)"
             "{"
               "a=H>=0.?refract(a,v,.75):refract(a,v,1.33);"
               "if(dot(a,v)<-.05)"
                 "x=a;"
             "}"
           "return normalize(x);"
         "}"
       "return ak(x,1.,.0101-abs(i)*.01);"
     "}"
 "}"
 "vec3 an(vec3 v,vec3 a)"
 "{"
   "vec3 c=vec3(0.),y=vec3(1.);"
   "I=1000.;"
   "af=0;"
   "for(int i=0;i<Y&&dot(y,y)>.001;i++)"
     "{"
       "vec2 f=al(v,a);"
       "if(f.y>=0.)"
         "{"
           "v+=a*f.x;"
           "vec3 d=am(v,f.y);"
           "c+=ai(y,a,v,d,f.y);"
           "a=ai(d,a,v,f.y);"
         "}"
       "else"
         "{"
           "if(f.y==-1.)"
             "c+=y*ap(a),c+=3.9*vec3(.15,.14,.15)*pow(clamp(dot(a,G),0.,2.),25.);"
           "else"
             " c+=y*w*2.;"
           "break;"
         "}"
     "}"
   "vec3 f=clamp(max(c,w/max(J*I*I,.5)),0.,1.);"
   "return f;"
 "}";

#endif // FRAG_CODE_H_
